sudo: required

# not necessary, but less confusing if defined
language: C

services:
  - docker

env:
  - DISTRO=debian:sid CC=gcc
  - DISTRO=fedora:rawhide CC=gcc
  - DISTRO=fedora:rawhide CC=clang
  - DISTRO=centos:7 CC=gcc

script:
  - >
    docker run
    -v `pwd`:/tmp/build
    -w /tmp/build
    -e CC=$CC
    $DISTRO /bin/bash -ex .travis.sh
