sudo: required

# not necessary, but less confusing if defined
language: C

services:
  - docker

env:
  - DISTRO=debian:sid COMPILER=gcc
  - DISTRO=fedora:rawhide COMPILER=gcc
  - DISTRO=fedora:rawhide COMPILER=clang
  - DISTRO=centos:7 COMPILER=gcc

script:
  - >
    docker run
    -v `pwd`:/tmp/build
    -w /tmp/build
    -e COMPILER=$COMPILER
    $DISTRO /bin/bash -ex .travis.sh
